Bank.Web/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bank.Entities;
using Bank.Cores;
using Bank.Models;
using Bank.Infrastructures;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;

namespace Bank.Web.Controllers
{
    /// <summary>
    /// Assumption user after login successful and Use the Authorize to prevent Anonymous access this page
    /// </summary>
    //[Authorize]
    public class AccountsController : BaseController
    {
       // private IMapper _mapper { get; set; }
        private readonly IAccountRepository _accountRepository;
        public AccountsController(IAccountRepository accountRepository, IMapper mapper)
        {
            _accountRepository = accountRepository;
            //_mapper = mapper;
        }

        // GET: Accounts
        public async Task<IActionResult> Index()
        {
            return View(await _accountRepository.GetAll());
        }
        public async Task<IActionResult> Transactions()
        {
            return View(await _accountRepository.GetTransactions());
        }
        // GET: Accounts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var account = await _accountRepository.Get(id);
            if (account == null)
            {
                return NotFound();
            }

            return View(account);
        }

        // GET: Accounts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Accounts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Use AccountModel instead of Account for validation model
        /// </summary>
        /// <param name="account"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AccountNumber,AccountName,Password,ConfirmPassword, Balance")] AccountCreateModel accountModel)
        {
            try
            {
                //Use ModelState to prevent the external incomming attack, rules validate in DataAnnotations of AccountCreateModel class
                if (ModelState.IsValid)
                {
                    //Move mapping to extenstions function or using mapper to map
                    // Account account = _mapper.Map<AccountCreateModel, Account>(accountModel);
                    Account account = new Account()
                    {
                        AccountNumber = accountModel.AccountNumber,
                        AccountName = accountModel.AccountName,
                        Password = accountModel.Password,
                        Balance = accountModel.Balance,
                    };

                    await _accountRepository.Add(account);
                    return RedirectToAction("Index");
                }
            }
            catch (BankException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }


            return View(accountModel);
        }

        // GET: Accounts/Edit/5
        public async Task<IActionResult> Deposit(int? id)
        {
            return await GetEditModel(id, ActionType.Deposit);
        }

        public async Task<IActionResult> Withdraw(int? id)
        {
            return await GetEditModel(id, ActionType.Withdraw);
        }
        public async Task<IActionResult> Tranfer(int? id)
        {
            return await GetEditModel(id, ActionType.Tranfer);
        }
        private async Task<IActionResult> GetEditModel(int? id, ActionType type)
        {
            if (id == null)
            {
                return NotFound();
            }

            var account = await _accountRepository.Get(id);
            if (account == null)
            {
                return NotFound();
            }

            return View("Edit", new AccountEditModel()
            {
                AccountID = account.AccountID,
                AccountName = account.AccountName,
                AccountNumber = account.AccountNumber,
                RowVersion = account.RowVersion,
                Balance = account.Balance,
                ActionType = type,

            });
        }



        // POST: Accounts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(byte[] rowVersion, ActionType ActionType, [Bind("AccountID,AccountNumber,AccountName,Balance,Amount,TranferNumber")] AccountEditModel account)
        {
            try
            {
                switch (ActionType)
                {
                    case ActionType.Deposit:
                        await _accountRepository.DepositAmount(rowVersion, account);
                        break;
                    case ActionType.Withdraw:
                        await _accountRepository.WithdrawAmount(rowVersion, account);
                       
                        break;
                    case ActionType.Tranfer:
                        Account senderAccount = null;
                        Account reciverAccount = null;

                        if (_accountRepository.IsValidAccount(account, out senderAccount, out reciverAccount))
                        {
                            await Task.Run(() => { _accountRepository.TranferAmount(rowVersion, account, senderAccount, reciverAccount); });
                        }
                        break;
                    default:
                        break;
                }



                return RedirectToAction("Index");
            }
            //catch (DbUpdateConcurrencyException ex)
            //{

            //    ModelState.AddModelError(string.Empty, "The record you attempted to edit "
            //        + "was modified by another user after you got the original value.");
            //    account.RowVersion = rowVersion;
            //}
            catch (BankException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }

            account.ActionType = ActionType;
            account.RowVersion = rowVersion;
            return View(account);
        }

        // GET: Accounts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var account = await _accountRepository.Get(id);
            if (account == null)
            {
                return NotFound();
            }

            return View(account);
        }

        // POST: Accounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _accountRepository.Delete(id);
            return RedirectToAction("Index");
        }

        private bool AccountExists(int id)
        {
            var result = _accountRepository.Get(id);
            return (result.IsCompleted && result.Result != null);
        }

        public IActionResult ConcurencyTest()
        {
            _accountRepository.ConcurencyTest();
            return Ok();
        }
    }
}

Bank.Web/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;


namespace Bank.Web.Controllers
{
   
    public class BaseController : Controller
    {
       
    }
}

Bank.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;


namespace Bank.Web.Controllers
{

    public class HomeController : BaseController
    {
        public IActionResult Index()
        {
            //var a = (int)(object)"a";
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

Bank.Web/Views/Accounts/Create.cshtml
@model Bank.Models.AccountCreateModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Account Manager</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="AccountNumber" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="AccountNumber" class="form-control" />
                <span asp-validation-for="AccountNumber" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="AccountName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="AccountName" class="form-control" />
                <span asp-validation-for="AccountName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Password" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ConfirmPassword" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ConfirmPassword" class="form-control" />
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Balance" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Balance" class="form-control" />
                <span asp-validation-for="Balance" class="text-danger"></span>
            </div>
        </div>
      
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Bank.Web/Views/Accounts/Delete.cshtml
@model Bank.Entities.Account

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Account</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="AccountID" />
        <dt>
            @Html.DisplayNameFor(model => model.AccountNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AccountNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AccountName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AccountName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Balance)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Balance)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

Bank.Web/Views/Accounts/Details.cshtml
@model Bank.Entities.Account

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Account</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AccountNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AccountNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AccountName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AccountName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Balance)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Balance)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.AccountID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Bank.Web/Views/Accounts/Edit.cshtml
@model Bank.Models.AccountEditModel

@{
    ViewData["Title"] = "Edit";
  
        string label = "";
        switch (Model.ActionType)
        {
            case Bank.Models.ActionType.Deposit:
                label = "Enter Deposit Amount";
                break;
            case Bank.Models.ActionType.Withdraw:
                label = "Enter to Withdraw Amount";
                break;
            case Bank.Models.ActionType.Tranfer:
                label = "Enter to Tranfer Amount";
                break;
            default:
                break;
         }         
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Account</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="AccountID" />
      
        <input type="hidden" asp-for="RowVersion" />
        <input type="hidden" asp-for="ActionType" />
        <div class="form-group">
            <label asp-for="AccountNumber" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="AccountNumber" class="form-control" readonly />
                <span asp-validation-for="AccountNumber" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="AccountName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="AccountName" class="form-control" readonly/>
                <span asp-validation-for="AccountName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Balance" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Balance" class="form-control" readonly/>
                <span asp-validation-for="Balance" class="text-danger"></span>
            </div>
        </div>
        @{
            if (Model.ActionType == Bank.Models.ActionType.Tranfer)
            {
                <div class="form-group">
                    <label class="col-md-2 control-label"> Account Number Tranfer </label>
                    <div class="col-md-10">
                        <input asp-for="TranferNumber" class="form-control" />
                        <span asp-validation-for="TranferNumber" class="text-danger"></span>
                    </div>
                </div>

            }
        }

        <div class="form-group">
            <label class="col-md-2 control-label"> @label </label>
            <div class="col-md-10">
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
        </div>
       


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Bank.Web/Views/Accounts/Index.cshtml
@model IEnumerable<Bank.Entities.Account>

@{
    ViewData["Title"] = "Account List";
}

<h2>Account List</h2>

<p>
    <a asp-action="ConcurencyTest">Concurency Test</a>
</p>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.AccountNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AccountName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Balance)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedDate)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AccountNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AccountName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Balance)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                <a asp-action="Deposit" asp-route-id="@item.AccountID">Deposit Amount</a> |
                <a asp-action="Withdraw" asp-route-id="@item.AccountID">Withdraw Amount</a> |
                <a asp-action="Tranfer" asp-route-id="@item.AccountID">Tranfer Amount</a> 
                @*<a asp-action="Details" asp-route-id="@item.AccountID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.AccountID">Delete</a>*@
            </td>
        </tr>
}
    </tbody>
</table>

Bank.Web/Views/Accounts/Transactions.cshtml
@model IEnumerable<Bank.Entities.AccountTransaction>

<h2>Transaction List</h2>

                      <table class="table">
                          <thead>
                              <tr>
                                  <th>
                                     Account Number
                                  </th>
                                  <th>
                                      Account Name
                                  </th>
                                  <th>
                                     Desciption
                                  </th>
                                  <th>
                                     Transaction Date
                                  </th>
                                
                                 
                              </tr>
                          </thead>
                          <tbody>
                              @foreach (var item in Model)
                              {
                                  <tr>
                                      <td>
                                          @Html.DisplayFor(modelItem => item.Account.AccountNumber)
                                      </td>
                                      <td>
                                          @Html.DisplayFor(modelItem => item.Account.AccountName)
                                      </td>
                                      <td>
                                          @Html.DisplayFor(modelItem => item.Description)
                                      </td>
                                      <td>
                                         @(((DateTime)item.TranDate).ToString("mm/dd/yyyy hh:mm"))
                                      </td>
                                    
                                  </tr>
                              }
                          </tbody>
                      </table>

Bank.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Bank.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Bank.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<div class="row">
    <div class="col-md-3">
        <h2>Simple Bank</h2>
     
    </div>
    
</div>

Bank.Web/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bank.Web</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Bank.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Accounts" asp-action="Index">Account Manager</a></li>
                    <li><a asp-area="" asp-controller="Accounts" asp-action="Transactions">Transactions</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Bank.Web</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>